### PR TITLE
Update forum icons

### PR DESCRIPTION
**Pull request by TimMoore**
These are the new forum icons we got from @rasummer.

I don't have a local development environment for playframework.com, so I haven't done any testing, but this is a straightforward replacement of existing image files.

### CODE REVIEW

**Comment by mkurz** [comment]
It seems you updated only the involved dot png files, however did not update the svg files:
* https://github.com/playframework/playframework.com/blob/3ec2c260a1f4bcf882b54affb80bc544aa2980d6/public/images/home/involved.svg
 * https://github.com/playframework/playframework.com/blob/3ec2c260a1f4bcf882b54affb80bc544aa2980d6/public/images/home/involved%402x.svg

So I got a bit confused now. Anyway, the svg files are not really used as far as I can tell. Maybe we should just remove them to avoid confusion and since they are outdated anyway...

**Comment by TimMoore** [comment]
Sorry, I don't really remember all of the context for this. I probably overlooked the SVG files if they weren't referenced in any templates. I guess there is value in having vector source files in case of future editing needs. I wonder if @rasummer still has them.

**Comment by mkurz** [comment]
Nothing to worry about, I already edited the png files in #454 and that's ok.

**Comment by TimMoore** [comment]
OK in that case I suppose removing the SVG files is a good idea. Thanks for your work, @mkurz!

**Pull request merged**
