### PR TITLE
Add example projects to Play downloads page

### PR DESCRIPTION
**Pull request by gmethvin**
Adds an example projects section to the Play download page at the top of the download page:

screenshot

/cc @corruptmemory

Once we've updated the API to allow us to fetch the sample project names, we should be able to use that for metadata instead of the hard-coded JSON.

### CODE REVIEW

**Comment by wsargent** [comment]
Looks good -- I'd like to talk about the naming of projects though, as I think the seed and intro projects need to be revised.

**Comment by gmethvin** [comment]
@wsargent Agreed. We need better naming to clarify what each is for. We could also add a "description" property that provides a longer description below each template.

**Comment by corruptmemory** [comment]
Woot!  Looks good to me!  You guys are great! Thanks!

**Comment by gmethvin** [comment]
@wsargent I modified the names of the projects (edited the screenshot). We can use this temporarily so we can update the Play docs to refer to it in getting started, then update again later to use the API.

I also made some other edits to clean up and clarify that page, and fix the alignment of the releases tables.

**Comment by wsargent** [comment]
LGTM

**Pull request merged**
