### PR TITLE
updated lightbend banner

### PR DESCRIPTION
**Pull request by rasummer**
@marcospereira this updates the Lightbend top banner per a request by @theotown and approved by @ennru. 

It removes the drop down nav from the Lightbend.com banner, and focuses the user on a single promo item - similar to Akka.io. 

play-lightbend-banner

I've also removed  old logos that are no longer needed, and updated fonts, as we switched to Roboto on LB.com, and no longer use Source Sans Pro.  Added some preconnect links for Google Fonts. 

Could you be kind enough to review/approve/deploy if all looks good. 

Thanks Rich

### CODE REVIEW

**Review by ignasi35 — APPROVED** [review]

**Comment by theotown** [comment]
Thanks Ignasi!

**Comment by rasummer** [comment]
Thanks @ignasi35, does this auto deploy?

**Comment by ignasi35** [comment]
it's manual. Just did it
 
https://www.playframework.com/

**Comment by mkurz** [comment]
Looks like something went wrong:
Screenshot from 2021-08-30 19-04-27

**Comment by rasummer** [comment]
Looks like the CSS was cached for a little while. It is now showing correctly on my browser.

**Comment by ignasi35** [comment]
Browser caches. 😒

Using Shift+Ctrl+R solves it, but it's not great.

**Comment by rasummer** [comment]
I will send a PR and put a version number into the oss-banner.css file that the main CSS calls.

**Comment by mkurz** [comment]
> Using Shift+Ctrl+R solves it, but it's not great.

It does _not_ solve it for me. I tried ctrl+f5 as well, tried incognito, tried firefox, tried chrome beta which never accessed playframework.com before.

**Comment by mkurz** [comment]
Maybe a cache from a cdn or something.

**Comment by rasummer** [comment]
I think this should fix it: https://github.com/playframework/playframework.com/pull/448

**Pull request merged**
