### PR TITLE
Added Support page.

### PR DESCRIPTION
**Pull request by rstento**
As discussed with team, added a Support tab and page.

### CODE REVIEW

**Comment by marcospereira** [comment]
See #190 for styling corrections. :-)

**Comment by rstento** [comment]
I noticed the inconsistencies too, but was not sure how to fix them. Thanks
@marcospereira.

Ruth Stento
User Experience Lead
Lightbend

512-818-6459
<http://lightbend.com>

**Comment by marcospereira** [comment]
@rstento the support page is now live: 

https://playframework.com/support

Thank you!

**Comment by mkurz** [comment]
https://www.lightbend.com/consulting
and
https://www.lightbend.com/training
return 404

**Comment by rstento** [comment]
Thanks Marcos and Matthias!

I've made a PR to fix the broken links.



Ruth Stento
User Experience Lead
Lightbend

512-818-6459
<http://lightbend.com>

**Pull request merged**
