### PR TITLE
Update gettingStarted.scala.html

### PR DESCRIPTION
**Pull request by theotown**
These are the proposed changes I'd like to implement with guidance from @rstento -- @ignasi35 was involved in crafting these updates.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @theotown,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by theotown** [comment]
Apologies for not filing an issue first. I'm learning that this is the normal practice.

**Review by ignasi35 — APPROVED** [review]

**Comment by theotown** [comment]
Hey @rstento I believe you did something here, but I'm not seeing anything...

**Comment by rstento** [comment]
@theotown, no I made the change in the playframework repo, to the docs. Your change is in the Website pages. I don't have permissions to merge your PR.

**Comment by ignasi35** [comment]
@rstento I understand by your comment that this is ready to merge?

**Comment by theotown** [comment]
From my POV, this is all good to go. Ruth has been making some changes to the docs, not this page. Once verified that it looks good (who does that?), then we can push :-)

**Comment by ignasi35** [comment]
> Once verified that it looks good (who does that?), ...

Usually a maintainer (e.g. me). But since this impacts copy we usually ask @rstento or @thothmoses for a second approval.

**Comment by theotown** [comment]
So this requires building the Play site and verifying it's ok, correct?
Since this is not something I've done (and don't know if I should try it!),
I'll leave that to others ;-)

>

**Comment by rstento** [comment]
> So this requires building the Play site and verifying it's ok, correct? Since this is not something I've done (and don't know if I should try it!), I'll leave that to others ;-)
> […](#)

@ignasi35, I tried, but failed to build the playframework.com. I'm fine with what Oliver removed, if you can just verify that it looks OK when built, please merge this.

**Comment by ignasi35** [comment]
LGTM

Screenshot 2021-07-28 at 08 38 12

**Comment by ignasi35** [comment]
It's deployed.

**Comment by theotown** [comment]
Thank you Ignasi!!

**Pull request merged**
