### PR TITLE
Images now live on play framework domain

### PR DESCRIPTION
**Pull request by rasummer**
@ignasi35  Fixes issue when 3rd party privacy plugins prevent images loading from different domain

### CODE REVIEW

**Comment by ignasi35** [comment]
Is the move to the edges intentional?

Screenshot 2020-03-31 at 19 20 06

_Comparison of live site VS local site from this PR_

**Comment by rasummer** [comment]
Yes, we have more logos in the drop down now, so being wider is the desire. All sites now have it at full width.

**Comment by ignasi35** [comment]
Deployed

**Comment by rasummer** [comment]
Thank you kindly

**Pull request merged**
